rvm:
  - __REPLACEME1__

services:
  - postgresql

before_install:
  - nvm install node
  
os:
  - linux
  
script:
  - yarn install
  - bundle install
  - rake db:test:prepare
  - bundle exec rails test
